name: DayDream
favicon: null
layout_spectrum: 0.38618585490621626
typography_spectrum: 0.9889981292653829
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7968506228644401
  lightness: 0.014978335704654455
  saturation: 0.7483936145436019
  rhythmicContrast: 0.19883803161792457
purpose: []
